# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cronometro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Lambda
from xml.dom.pulldom import parseString
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_dis = QtWidgets.QComboBox(self.centralwidget)
        self.combo_dis.setGeometry(QtCore.QRect(120, 40, 141, 31))
        self.combo_dis.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.combo_dis.setObjectName("combo_dis")
        self.combo_dis.addItem("")
        self.combo_dis.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(990, 80, 111, 16))
        self.label_3.setObjectName("label_3")
        self.button_correr = QtWidgets.QPushButton(self.centralwidget)
        self.button_correr.setGeometry(QtCore.QRect(980, 100, 121, 31))
        self.button_correr.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.button_correr.setObjectName("button_correr")
        self.button_parar = QtWidgets.QPushButton(self.centralwidget)
        self.button_parar.setGeometry(QtCore.QRect(980, 140, 121, 31))
        self.button_parar.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.button_parar.setObjectName("button_parar")
        self.button_carrera = QtWidgets.QPushButton(self.centralwidget)
        self.button_carrera.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.button_carrera.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 0);")
        self.button_carrera.setObjectName("button_carrera")
        self.button_meta = QtWidgets.QPushButton(self.centralwidget)
        self.button_meta.setGeometry(QtCore.QRect(180, 200, 131, 31))
        self.button_meta.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 0);")
        self.button_meta.setObjectName("button_meta")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 250, 1201, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1199, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.table_corredores = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.table_corredores.setGeometry(QtCore.QRect(0, 0, 1201, 241))
        self.table_corredores.setObjectName("table_corredores")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 150, 161, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 190, 61, 16))
        self.label_6.setObjectName("label_6")
        self.edit_corredor = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_corredor.setGeometry(QtCore.QRect(690, 180, 141, 31))
        self.edit_corredor.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.edit_corredor.setObjectName("edit_corredor")
        self.button_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar.setGeometry(QtCore.QRect(850, 170, 41, 41))
        self.button_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/buscar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_buscar.setIcon(icon)
        self.button_buscar.setIconSize(QtCore.QSize(38, 38))
        self.button_buscar.setObjectName("button_buscar")
        self.button_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.button_guardar.setGeometry(QtCore.QRect(980, 180, 121, 31))
        self.button_guardar.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.button_guardar.setObjectName("button_guardar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(900, 190, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_8.setObjectName("label_8")
        self.button_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.button_enviar.setGeometry(QtCore.QRect(1150, 200, 41, 41))
        self.button_enviar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/enviar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_enviar.setIcon(icon1)
        self.button_enviar.setIconSize(QtCore.QSize(38, 38))
        self.button_enviar.setObjectName("button_enviar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(890, 10, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 90, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 100, 121, 16))
        self.label_9.setObjectName("label_9")
        self.button_buscar_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar_3.setGeometry(QtCore.QRect(280, 80, 41, 41))
        self.button_buscar_3.setText("")
        self.button_buscar_3.setIcon(icon)
        self.button_buscar_3.setIconSize(QtCore.QSize(38, 38))
        self.button_buscar_3.setObjectName("button_buscar_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(360, 20, 81, 16))
        self.label_10.setObjectName("label_10")
        self.combo_dis_2 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_dis_2.setGeometry(QtCore.QRect(360, 40, 141, 31))
        self.combo_dis_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.combo_dis_2.setObjectName("combo_dis_2")
        self.combo_dis_2.addItem("")
        self.combo_dis_2.addItem("")
        self.combo_dis_2.addItem("")
        self.combo_dis_2.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(960, 500, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 510, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.button_buscar.clicked.connect(self.buscarCorredor)
        self.button_buscar_3.clicked.connect(self.buscar)
        self.button_guardar.clicked.connect(self.guardar)
        self.button_enviar.clicked.connect(self.enviar)
        self.button_parar.clicked.connect(self.parar)
        self.button_correr.clicked.connect(self.correr)
        self.button_carrera.clicked.connect(self.enCarrera)
        self.button_meta.clicked.connect(self.distancia)
        # self.table_corredores.setRowCount(4)
        # self.table_corredores.setColumnCount(2)
        self.table_corredores.setSelectionModel(0,0, QTableWidgetItem("Name"))
        self.table_corredores.setItem(0,1, QTableWidgetItem("City"))
        self.table_corredores.setItem(1,0, QTableWidgetItem("Aloysius"))
        self.table_corredores.setItem(1,1, QTableWidgetItem("Indore"))
        self.table_corredores.setItem(2,0, QTableWidgetItem("Alan"))
        self.table_corredores.setItem(2,1, QTableWidgetItem("Bhopal"))
        self.table_corredores.setItem(3,0, QTableWidgetItem("Arnavi"))
        self.table_corredores.setItem(3,1, QTableWidgetItem("Mandsaur"))

        
        self.distancia = 'Todas'
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    
        #self.button_buscar.hide()
    def distancia(self):
        self.distancia = self.combo_dis.currentText()
        print(self.distancia)
    def mostrarHora(self):
            self.label_11.setText(time.strftime("%H:%M:%S"))
            QtCore.QTimer.singleShot(1000, self.mostrarHora)
    def enviar(self):
        print('Enviar')
    def buscarCorredor(self):
        self.corredor = self.edit_corredor.text()
        print(self.corredor)
    def guardar(self):
        self.tiempoCorredor = time.strftime("%H:%M:%S")
        print(self.tiempoCorredor)
    def buscar(self):
        self.corredor = self.lineEdit.text()
        print(self.corredor)
    def correr(self):
        self.inicio = time.strftime("%H:%M:%S")
        print(self.inicio)
    def parar(self):
        self.final = time.strftime("%H:%M:%S")
        print(self.final)
    def enCarrera(self):
        self.estado = True
        print(self.estado)
    def enMeta(self):
        self.estado = False
        print(self.estado)
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_dis.setItemText(0, _translate("MainWindow", "12k"))
        self.combo_dis.setItemText(1, _translate("MainWindow", "27k"))
        self.label.setText(_translate("MainWindow", "Distancia"))
        self.label_2.setText(_translate("MainWindow", "Elegir distancia"))
        self.label_3.setText(_translate("MainWindow", "Control Cronometro"))
        self.button_correr.setText(_translate("MainWindow", "CORRER"))
        self.button_parar.setText(_translate("MainWindow", "PARAR"))
        self.button_carrera.setToolTip(_translate("MainWindow", "<html><head/><body><p>Carrera</p></body></html>"))
        self.button_carrera.setText(_translate("MainWindow", "EN CARRERA"))
        self.button_meta.setToolTip(_translate("MainWindow", "<html><head/><body><p>Meta</p></body></html>"))
        self.button_meta.setText(_translate("MainWindow", "EN META"))
        self.label_5.setText(_translate("MainWindow", "Ingrese el numero del corredor"))
        self.label_6.setText(_translate("MainWindow", "# Corredor"))
        self.button_guardar.setText(_translate("MainWindow", "GUARDAR"))
        self.label_7.setText(_translate("MainWindow", "Marcar tiempo"))
        self.label_8.setText(_translate("MainWindow", "Estado del corredor"))
        self.button_enviar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enviar Tiempos</p></body></html>"))
        self.mostrarHora()
        
        self.label_9.setText(_translate("MainWindow", "# Documento"))
        self.label_10.setText(_translate("MainWindow", "Elegir categoria"))
        self.combo_dis_2.setItemText(0, _translate("MainWindow", "Elite masculino"))
        self.combo_dis_2.setItemText(1, _translate("MainWindow", "Elite femenino"))
        self.combo_dis_2.setItemText(2, _translate("MainWindow", "Master maculino"))
        self.combo_dis_2.setItemText(3, _translate("MainWindow", "Master femenino"))
        
        #self.label_11.setText(time.strftime("%H:%M:%S"))
        self.label_12.setText(time.strftime("%d/%m/%y"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
   
    
    MainWindow.show()
    sys.exit(app.exec_())
    
